name: assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  sqflite:
  path:
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  connectivity_plus: ^6.0.3
  flutter_contacts: ^1.1.8
  lottie: ^3.1.2
  onscreen_num_keyboard: ^1.0.4
  intl: ^0.19.0
  qr_scanner_with_effect: ^1.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/svg/
    - assets/img/
    - lib/app/config/.env
    - assets/lottiefiles/
  uses-material-design: true

